### ISSUE TITLE
TPM Attestation

### ISSUE THREAD

**Issue by My1** [lbuchs/WebAuthn#11]
are there plans to add TPM attestation?

**Comment by lbuchs** [comment]
no concrete plan -  do you know any device/testcase which operates with tpm?

**Comment by My1** [comment]
sadly not yet anything to directly test but isnt MS iirc using TPM Fido/webauthn stuff already?
https://www.theverge.com/2018/11/20/18104376/microsoft-account-no-password-windows-hello-fido2-support
![image](https://user-images.githubusercontent.com/6696524/66040452-b8444080-e517-11e9-9c12-ce046339f4d7.png)

**Comment by hafkenscheid** [comment]
Is there any news on this topic?

**Comment by lbuchs** [comment]
Windows Hello is using RS256, which is now supported. it uses the attestation format "none", you can test it using windows hello on the [demo application](https://webauthn.lubu.ch/_test/client.html): check attestation format "none", deselect all root certificates.

According to [dev guide](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication) you will _"receive a TPM attestation statement, set attestation to "direct" when calling the create API. TPM attestation is a best effort. Only PCs with TPM 2.0 will return a TPM attestation statement, and the attestation process could fail for a variety of reasons."_

I could not receive a tpm attestation, I got always none (my hardware seems to be too old). Have to test on other hardware.

**Comment by ifmx-dev** [comment]
I receive a tpm attestation on createProcess. There I get a failure, because the tpm attestation format ist not in the config. When I add it to the acceptet formats it does not work because I get the wrong arguments for tpm.

**Comment by My1** [comment]
> I receive a tpm attestation on createProcess. There I get a failure "invalid attestation format" because the tpm attestation format ist not in the config. When I add it to the accepted formats it does not work because I get "wrong arguments for attestation format tpm".

maybe if you set attestation formats to none only, windows will also not spawn an attestation.

@lbuchs maybe one thing that could be done about some attestation chaos is that if no attestation is allowed (list includes none, while not being none only) to just drop attestations that arent supported or invalid.

**Comment by lbuchs** [comment]
TPM supported with 8138bf5
