### ISSUE TITLE
expose whether UV was used or not

### ISSUE THREAD

**Issue by My1** [lbuchs/WebAuthn#16]
currently one cannot directly pull whether UV was used on any given auth/register.

especially on uv=preferred attempts one might wanna know whether UV was used or not to add that info to add server-side validation of UV in the future (to prevent thieves from changing the UV value in the request and do bad stuff)

on an auth attempt it isnt too hard to pull the value out since it's at a fixed byte (32 counting from 0) offset of the authenticatordata

but at the registration the authenticator data is part of the Attestation object, a CBOR array, something one cant take apart THAT easily or quickly, so it would be useful if the processcreate/processget just give out this fact.

**Comment by lbuchs** [comment]
it's now exposed in the processCreate stdClass object as userPresent and userVerified flag.

**Comment by My1** [comment]
cool thanks.
