### ISSUE TITLE
Ivalid root certificat if webauthn.lubu.ch tested with hypersecu USB key

### ISSUE THREAD

**Issue by hermann77** [lbuchs/WebAuthn#19]
I would like to use this library, but if I test it on
webauthn.lubu.ch
with a 'hypersecu' USB key:

'Ivalid root certificat' comes up if I try to make a new registration.

**Comment by lbuchs** [comment]
hypersecu has a new (second) root ca, i've added it to the test script, so it should probably work now.

Committed in https://github.com/lbuchs/WebAuthn/commit/d52116a0a81a76a6e27f865a88289282dd9c5c3b

**Comment by hermann77** [comment]
Thank you very much! Test registration/login page works now.
