### ISSUE TITLE
Microsoft HELLO with EDGE

### ISSUE THREAD

**Issue by kkr0kk** [lbuchs/WebAuthn#2]
Seem to be not working with HELLO
<b>Fatal error</b>:  Uncaught exception 'WebAuthn\WebAuthnException' with message 'Unsupported simple value 5.'
Stack trace:
#0 /var/www/htdocs/include/CBOR/CborDecoder.php(109): WebAuthn\CBOR\CborDecoder::_parseSimple(5) --> ERROR
#1 /var/www/htdocs/include/CBOR/CborDecoder.php(70): WebAuthn\CBOR\CborDecoder::_parseFloatSimple(5, Object(WebAuthn\Binary\ByteBuffer), 23)
#2 /var/www/htdocs/include/CBOR/CborDecoder.php(200): WebAuthn\CBOR\CborDecoder::_parseItem(Object(WebAuthn\Binary\ByteBuffer), 23)
#3 /var/www/htdocs/include/CBOR/CborDecoder.php(186): WebAuthn\CBOR\CborDecoder::_parseMap(Object(WebAuthn\Binary\ByteBuffer), 23, 3)
#4 /var/www/htdocs/include/CBOR/CborDecoder.php(75): WebAuthn\CBOR\CborDecoder::_parseItemData(5, 3, Object(WebAuthn\Binary\ByteBuffer), 23)
#5 /var/www/htdocs/include/CBOR/CborDecoder.php(33): WebAuthn\CBOR\CborDecoder::_parseItem(Object(WebAuthn\Binary\ByteBuffer), 23)
#6 /var/www/htdocs/include/Attestation/AttestationObject.php(21): WebAuthn\CBOR\CborDecoder: in <b>/var/www/htdocs/include/CBOR/CborDecoder.php</b> on line <b>127</b><br />

**Comment by lbuchs** [comment]
MS HELLO is not currently supported as it only supports RS256 algorithm. https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication
