### ISSUE TITLE
Latency on Registration

### ISSUE THREAD

**Issue by SeanHerbert** [lbuchs/WebAuthn#20]
Is there a way to decrease latency on registration (~4s). The latency on check registration is ~2s.

**Comment by lbuchs** [comment]
I don't have any latency. What platform do you use?

**Comment by SeanHerbert** [comment]
I tested your demo site using a Samsung S7 phone using the android-safetynet attestation format. I did a new registration using fingerprint. After the fingerprint registered (green check mark on alert message), it took ~4 seconds to alert "registration success" message. Check registration only took ~2 seconds. This is the latency I'm talking about. 

The setup I have is AWS EC2 instance running Amazon Linux AMI. My setup has that latency as well. Also I verified that webauthn.io is the same latency as well. 

I was hoping you knew if there was a way to make registration process faster. Thanks for your help!
