### ISSUE TITLE
Apple Attestation

### ISSUE THREAD

**Issue by royjr** [lbuchs/WebAuthn#24]
Add support for Apples attestation 
From: [https://github.com/abergs/fido2-net-lib/issues/184](https://github.com/abergs/fido2-net-lib/issues/184)

> Format came out last night: https://pr-preview.s3.amazonaws.com/alanwaketan/webauthn/pull/1491.html#sctn-apple-anonymous-attestation
> 
> Initial implementation here: [0d6410c](https://github.com/abergs/fido2-net-lib/commit/0d6410c4ad3b1103eb5a62cc85acc8b9e2a9c4af)
> 
> Borrowed initial test data from [webauthn4j/webauthn4j@9a7260b#diff-b16de03d04ad98253ba2011fc88e755f](https://github.com/webauthn4j/webauthn4j/commit/9a7260b3097da92113abf78ff0dc378f842cd50c#diff-b16de03d04ad98253ba2011fc88e755f)

**Comment by andryyy** [comment]
Any way to sponsor this @lbuchs ? :)

**Comment by lbuchs** [comment]
I've already done a draft at [feature/apple](https://github.com/lbuchs/WebAuthn/tree/feature/apple) branch. It's installed at my [demo version](https://webauthn.lubu.ch/_test/client.html), maybe someone with a apple device could test it and give a feedback if it works now :-)

**Comment by andryyy** [comment]
Can you contact me on info@servercow.de ? I would like to thank you for your work.

**Comment by andryyy** [comment]
It works great for me. :)

**Comment by lbuchs** [comment]
merged to master with 6f64e277
