### ISSUE TITLE
Invalid root certificates

### ISSUE THREAD

**Issue by redochka** [lbuchs/WebAuthn#28]
When testing with Chrome with WebAuthn tool enabled in the inspector, I get the invalid root certificate error.

How to update the certificate list available in _test/rootCertificates

Where did you get them?

**Comment by lbuchs** [comment]
If you use chromium dev tool, a self signed certificate is used. (Issuer: C=US, O=Chromium, OU=Authenticator Attestation, CN=Batch Certificate). So you can't check against a root ca; if you uncheck all root certificates, self signed certificates are accepted.
