### ISSUE TITLE
fido-u2f not working, invalid format.

### ISSUE THREAD

**Issue by brambo123** [lbuchs/WebAuthn#29]
I can't get my Yubikey working.

I encounter the following error:
`lbuchs\WebAuthn\WebAuthnException: unsupported alg:  in ...vendor/lbuchs/webauthn/src/Attestation/Format/U2f.php`

It looks like data is expected in $attStmt['alg'];
However 'attStmt' should not have any 'alg' at all following this page:
https://www.w3.org/TR/webauthn/#sctn-fido-u2f-attestation

**Comment by lbuchs** [comment]
Thanks, fixed in e62a661
