### ISSUE TITLE
PHP 8.1 Compatibility Issue

### ISSUE THREAD

**Issue by zorro1199** [lbuchs/WebAuthn#37]
ByteBuffer.php makes use of the broken `Serializable` interface and causes deprecation warnings with PHP 8.1. `__serialize()` should be used instead: [https://wiki.php.net/rfc/phase_out_serializable](https://wiki.php.net/rfc/phase_out_serializable)

**Comment by lbuchs** [comment]
Fixed in 9c85196e048fd7
