### ISSUE TITLE
Not working on Apple BigSur with Touch ID

### ISSUE THREAD

**Issue by feldsam** [lbuchs/WebAuthn#40]
Hi, this lib with example JS code is not working on macOS BigSur with Touch ID.

In Safari - it stops on `navigator.credentials.create` with not allowed error "This request has been canceled by the user."
 - probably caused by missing gestures? [ paragraph about Propagating User Gestures](https://webkit.org/blog/11312/meet-face-id-and-touch-id-for-the-web/)

In Chrome - the x5c field is missing in the CBOR object, so root CA can't be validated.
 - according to [section SELF(SURROGATE) Attestation](https://medium.com/webauthnworks/verifying-fido2-packed-attestation-a067a9b2facd) there is self-attestation allowed when `fmt == packed` and x5c is missing. Problem is on [this line](https://github.com/lbuchs/WebAuthn/blob/ca2c66efb141a4f24a84aac27a94505cfa2e4323/src/Attestation/Format/Packed.php#L83) where we should `return true` or hanle it differently on [this line](https://github.com/lbuchs/WebAuthn/blob/ca2c66efb141a4f24a84aac27a94505cfa2e4323/src/WebAuthn.php#L322)

btw,
- on this page https://webauthn.io it is working without problems but looks like the CBOR object is different
- iPhone with the latest iOS and Safari is working fine using Face ID

**Comment by lbuchs** [comment]
> it stops on navigator.credentials.create with not allowed error "This request has been canceled by the user."

Maybe you have just to select "internal" on the "type of authenticator" on the demo app. The getCreateArgs function of this library returns a object valid to the specs, so check if your implementation is correctly decoding the ArrayBuffer values.

> In Chrome - the x5c field is missing in the CBOR object, so root CA can't be validated.

If there is no x5c there is no root CA so there is no validation possible, and therefore the function `validateRootCertificate()` cannot return true. So if you don't want to fail in this case, you can set `$failIfRootMismatch` of `processCreate()` to false, then it will not throw a error, but return `rootValid=false` so you can decide yourself what you wanna do in this case.
Or you can deselect all root ca, then it won't check the root ca anyway so you have the same result like https://webauthn.io (looks like this page cannot verify any root ca).

**Comment by feldsam** [comment]
Hi, in meantime I found that it is a bug in Safari https://bugs.webkit.org/show_bug.cgi?id=224042
