### ISSUE TITLE
Question on RPID

### ISSUE THREAD

**Issue by wagner-robert** [lbuchs/WebAuthn#43]
On the surface, the RPID is essentially the domain URL. https://www.w3.org/TR/webauthn-1/#relying-party-identifier  
I was wondering if another identifier such as a random UUID could be used?

Reason - To hide the website URL from the token, or someone that found/stole a token.  FIDO in some instances has discoverable credentials. 
https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Overview.html 

**User login flows supported**

Example FIDO2/WebAuthn authenticator flows:
    Single factor: Username + FIDO2 credential
    Second factor: Username + password + FIDO2 credential
    Passwordless single factor: FIDO2 discoverable credential (a ‘discoverable credential’ stores user data on the authenticator)
    Passwordless MFA: FIDO2 discoverable credential + PIN

FIDO2 is also backwards-compatible with FIDO U2F authenticators
    Single factor: Username + FIDO U2F credential
    Second factor: Username + password + FIDO U2F credential

**Comment by lbuchs** [comment]
The domain is necessary to prevent phishing attacks. Because the rpid needs to be the domain name, it's impossible to login with a key on a different (phishing) domain. If you could set a random ID, a phishing site could use the same id.

**Comment by wagner-robert** [comment]
Thanks for the details... makes sense.  I notice they release WebAuthn level 2 in April 2021.  Any differences?
Any chance you could add a button for testing User Prescence? https://www.w3.org/TR/webauthn/#test-of-user-presence


Robert Wagner

________________________________

**Comment by lbuchs** [comment]
you can see userPresent (yes or no) in the server preview on the test app. It's almost every time "yes" because every authenticator I know has a button to click on to verify user precense, I don't know any authenticator who does login without user interaction.

**Comment by My1** [comment]
> you can see userPresent (yes or no) in the server preview on the test app. It's almost every time "yes" because every authenticator I know has a button to click on to verify user precense, I don't know any authenticator who does login without user interaction.

actually at the very least on windows and android platform auth you dont have an I'd say "solid" test of user presence.

On windows i could register as well as use a credential on the demo site with  bog-standard un-elevated copy of anydesk meaning that no sandboxing similar to admin applications or anything really is used on the FIDO prompt.
On android it's a bit less easy as I needed to enable accessibility and the prompt for the pattern I used was blacked out by either android itself or Samsung's GUI (xcover pro) however interaction was still very much possible.

on both you do have UV but if you can get a hold of the PIN/Pattern or whatever used for FIDO on those (which especially on windows likely isnt too hard using a keylogger, considering PIN-Windows arent even on privileged ground) and thereby get in without literally any presence requirement. Despite this Windows happily throws in the UV bit which I think isnt awesome.
