### ISSUE TITLE
MySQL saving

### ISSUE THREAD

**Issue by xTermy** [lbuchs/WebAuthn#5]
How to add key id to mysql database? What is needed to know what user is it?

**Comment by lbuchs** [comment]
![webauthn_db](https://user-images.githubusercontent.com/37619779/57612781-bcc28980-7575-11e9-97cd-6ac226ec5dce.png)


minimal requirement is to store the `credentialId` and  `credentialPublicKey` for a user, if you store the `signatureCounter` you have even more security.  It should be possible for a user to register multiple keys for his account, so it should be stored in a table connected n:1 to the user. 

If you want to validate a key after registration, you can save the `certificate` and maybe the `AAGUID` to. The AAGUID is a unique device type identifier, you could make a statistic which device types are used for your service, or block a device type if there should appear a security problem with a specific key in future.

**Comment by My1** [comment]
but one needs to be careful. according to a vardump I did of the session of the test page, the credential id and AAGUID are binary values, one might want to encode those to not break anything.

**Comment by BrunoFigueiraBarros** [comment]
After registering information, how will I consult it?
