### ISSUE TITLE
Doesn't work on Android (Firefox/Chrome)

### ISSUE THREAD

**Issue by qol3m** [lbuchs/WebAuthn#6]
In Firefox on Android (u2f enabled) "the page at https://webauthn.lubu.ch says: unknown error occured"

In Chrome on Android "webauthn.lubu.ch says Not implemented"

I checked all attestation statement formats.

I checked/unchecked all root certificates.

I run LineageOS (Android 8.1) and would like to use my fingerprint sensor.

**Comment by lbuchs** [comment]
Firefox for Android: I can reproduce the issue; webauthn seems to be not working on ff for android, also other examples like https://webauthn.io don't work.

Chrome on Android: "Not implemented" is the message of your browser. Whats your chrome version? Webauthn requires Chrome for Android release 70+.
