### ISSUE TITLE
Saving user data in resident key works well. Can we store sensitive data in key?

### ISSUE THREAD

**Issue by raroraca** [lbuchs/WebAuthn#63]
As we can save the blob data in the key. And these can be retrieved in clear form anytime. But is it possible that we can store some sensitive additional information in key, which can be only verified?

**Comment by lbuchs** [comment]
webauthn is to protect logins, not to store user data. For resident key you should not include personally identifying information, e.g., e-mail addresses or usernames, in the user handle, it should be random bytes. (check [specs](https://www.w3.org/TR/webauthn/#sctn-user-handle-privacy)).
