### ISSUE TITLE
Packagist is not up to date with the last version (v1.1.1)

### ISSUE THREAD

**Issue by BafS** [lbuchs/WebAuthn#67]
The last version was tagged 3 days ago (v1.1.1) but unfortunately packagist is not [auto-updated](https://packagist.org/about#how-to-update-packages) (https://packagist.org/packages/lbuchs/WebAuthn) and it is still in v1.1.0, would it be possible to fix this?

Thanks in advance

**Comment by lbuchs** [comment]
this is not maintained by me, you have to contact the maintainer there.

**Comment by BafS** [comment]
@m1guelpf could you add @lbuchs or me on packagist?

**Comment by BafS** [comment]
@m1guelpf would it be possible to add him on packagist? If not could we have a new name @lbuchs?

**Comment by m1guelpf** [comment]
@lbuchs What's your Packagist username? `lbuchs` returns no results...

**Comment by lbuchs** [comment]
It's not auto-updated, but there is a button at packagist to update (when logged in), usable for everyone, then it gets updated from here. When no one clicks the button, then → _"Existing packages without auto-updating (GitHub/BitBucket/GitLab/Gitea hook) will be crawled once a week for updates"_.
