### ISSUE TITLE
`ByteBuffer::equals` function unclear

### ISSUE THREAD

**Issue by rasteiner** [lbuchs/WebAuthn#68]
https://github.com/lbuchs/WebAuthn/blob/master/src/Binary/ByteBuffer.php#L188-L194
Here's the sourcecode:
```php
/**
 * @param string $buffer
 * @return bool
 */
public function equals($buffer): bool {
    return is_string($this->_data) && $this->_data === $buffer->data;
}
```

The docblock mentions $buffer should be a string, presumably the binary string representing the buffer, however the functions checks for a `$data` instance member that strings don't have. I actually expected other ByteBuffers to work, but the property there is called `_data` (with an underscore). Am I missing something?

**Comment by lbuchs** [comment]
thanks, that's a bug. I've fixed it in b57d37f30b465033677f4ab1705828237531cddb , now you can compare it with a string other with a other instance of ByteBuffer.
