### ISSUE TITLE
Prevent duplicate key registration

### ISSUE THREAD

**Issue by Leseratte10** [lbuchs/WebAuthn#69]
I've played around with the test page a bit trying to get this added to one of my websites, but there's one thing I'm missing: 

On sites like Google, or on test pages like [webauthn.io](https://webauthn.io/) when I try to register an authenticator that's already linked to my account, I get a message from my browser telling me to "Try a different key - you already registered this key, it doesn't need to be registered again."

When I do the same thing on your test page, it happily registers the same authenticator over and over again. Is there a special setting I have to set to be able to detect and block duplicate authenticators, or does the library not support that yet?

Haven't found anything in the readme or on the test page. All the values shown in the registration iFrame are also all different for all the registrations so I can't check for that (duplicate authenticator) myself, looks like that has to happen in the browser somehow like Google does - but how do I trigger that?

Looking at the spec, the related parameter seems to be [excludeCredentials](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialcreationoptions-excludecredentials). Is this supported by this library and if not, can that be added?

This feature is also recommended by the spec, if I interpret it correctly: 
> [Relying Parties](https://www.w3.org/TR/webauthn-2/#relying-party) SHOULD make use of the [excludeCredentials](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialcreationoptions-excludecredentials) and [user](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialcreationoptions-user).[id](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialuserentity-id) options to ensure that these different [credentials](https://www.w3.org/TR/webauthn-2/#public-key-credential) are [bound](https://www.w3.org/TR/webauthn-2/#bound-credential) to different [authenticators](https://www.w3.org/TR/webauthn-2/#authenticator).

**Comment by lbuchs** [comment]
you have to provide the Ids which are already registered to the function [`getCreateArgs`](https://github.com/lbuchs/WebAuthn/blob/b57d37f30b465033677f4ab1705828237531cddb/src/WebAuthn.php#L125) (Parameter `$excludeCredentialIds`).

On my demo this parameter is not used so you can register multiple times, it makes it easier for testing.
