### ISSUE TITLE
Indefinite length is not supported.

### ISSUE THREAD

**Issue by DigitalEnki** [lbuchs/WebAuthn#7]
When using a security key on Chrome, I'm getting this error response.

On your demo URL, my security key works correctly, however when cloning your library and running the test, I get `{"success":false,"msg":"Indefinite length is not supported."}`

I'm running apache2 with php7.0, I also set up en envrionment with php5.6 but have the same issue.

Any ideas?

**Comment by My1** [comment]
what key are you using? also maybe try a PHP version that isnt EOL.
