### ISSUE TITLE
Missing implementation of hybrid Authenticator Transport Enumeration

### ISSUE THREAD

**Issue by JohnyRicio** [lbuchs/WebAuthn#72]
I tried to implement this library with combination of using android phone as auth factor. It is works for create authentication through cell phone, but when I want to login and authenticate by it that it is unsuccesfull. 

Method getGetArgs didn't support transport hybrid. See docs: https://w3c.github.io/webauthn/#enum-transport

Please add support of it.

**Comment by lbuchs** [comment]
this is a part of Webauthn Level 3, which is currently a First Public Working Draft.

⚠️ This will shift arguments of `lbuchs\WebAuthn->getGetArgs()`

**Comment by lbuchs** [comment]
implemented in [v2.0.1](https://github.com/lbuchs/WebAuthn/releases/tag/v2.0.1)
