### ISSUE TITLE
allow userVerification discouraged

### ISSUE THREAD

**Issue by My1** [lbuchs/WebAuthn#8]
currently it is only possible to "require" (you have to verify the user) or "prefer" (if you can verify the user, please do so) the userVerification.

if you want to use the device only as a second factor it may not be wanted to use the verification of the Fido device. this is generally possible by setting userVerification to discouraged

https://github.com/lbuchs/WebAuthn/blob/master/WebAuthn.php#L114

hacking that line to replace `preferred` with `discouraged` makes it register fine without verification, but apparently there is no obvious way to do the same for logging in.

okay for login one has to make the following for getgetargs:
~~~php
$args->publicKey->userVerification = 'discouraged';
~~~

I think I can work on a pull request.

**Comment by lbuchs** [comment]
Fixed. You can now pass string 'discouraged' to the function getCreateArgs(). And I've added the same parameter to the function getGetArgs().
