### ISSUE TITLE
Support for kty 1 (OKP/ed25519)

### ISSUE THREAD

**Issue by DKhalil** [lbuchs/WebAuthn#80]
Right now when supplying a key in this format it gets rejected "invalid key type", are you planning on adding support for it?

**Comment by lbuchs** [comment]
it's supported with PHP [Sodium](https://www.php.net/manual/en/book.sodium.php) (or [Sodium Compat](https://github.com/paragonie/sodium_compat) )

**Comment by DKhalil** [comment]
Silly me. I had 2.0 installed. Sorry, works now of course!
