### ISSUE TITLE
Authentication no longer possible in Safari v17.4.1 (latest)

### ISSUE THREAD

**Issue by l1nk-16** [lbuchs/WebAuthn#88]
Tested in Safari 17.4.1 (latest), Safari Technology Preview 191 (latest) under macOS Sonoma 14.4.1 (latest).

**Safari Technology Preview 188 Release Notes:**
WebAuthn - Resolved Issues
Fixed getClientCapabilities to align with WebAuthn standards to use a record type with camelCase values. ([272998@main](https://commits.webkit.org/272998@main)) (120442670)

**Safari Technology Preview 189 Release Notes:**
WebAuthn - Resolved Issues
Fixed navigator.credentials.create() rejects with “NotAllowedError: Operation Failed” after a conditional UI request is aborted. ([273918@main](https://commits.webkit.org/273918@main)) (109936742)

**Comment by lbuchs** [comment]
what's the error you get?

**Comment by l1nk-16** [comment]
It's the error code 10: user not verified during authentication

I have set $requireUserVerification = true

**Comment by lbuchs** [comment]
it happens on registration or on validation?

Don't think that this has something to do with this library, `userVerification` is a flag returned by the authenticator. When it's set to false but you have authenticated yourself, then it's a problem of the authenticator (macOS).

**Comment by l1nk-16** [comment]
It happens on validation.

Ok, but why does the process still work on www.webauthn.io using the same requirements?
