### ISSUE TITLE
Support for native Android apps - FIDO2 API for Android

### ISSUE THREAD

**Issue by armatys** [lbuchs/WebAuthn#94]
I'm trying to integrate this library, and get it working with an Android app (via [FIDO2 API for Android](https://developers.google.com/identity/fido/android/native-apps)).

From [WebAuthn spec](https://www.w3.org/TR/webauthn/#rp-id):
> Other specifications mimicking the [WebAuthn API](https://www.w3.org/TR/webauthn/#web-authentication-api) to enable WebAuthn [public key credentials](https://www.w3.org/TR/webauthn/#public-key-credential) on non-Web platforms (e.g. native mobile applications), MAY define different rules for binding a caller to a [Relying Party Identifier](https://www.w3.org/TR/webauthn/#relying-party-identifier).

The above seems to be the case for native Android apps, because when an Android app generates `ClientData` (which will be sent to the backend), it looks something like this:
```json
{
  "type":"webauthn.get",
  "challenge":"6wihG...",
  "origin":"android:apk-key-hash:A0JAQL4...",
  "androidPackageName":"com.example.myapp"
}
```

Notice that on Android (see [verifying origin](https://developer.android.com/identity/sign-in/credential-manager#verify-origin)) the `origin` doesn't start with `https://...` (which is required by WebAuthn library), but it uses `android:apk-key-hash:...`. The above JSON is generated by the "FIDO2 for Android" library, and it's not possible to set a custom origin. It's also not possible to modify the origin manually, because then the signature will be incorrect.

I wonder if the WebAuthn library could somehow support this use case, e.g. by allowing to specify a list of allowed Android apk-key-hashes, or maybe throwing a specific error, which could be handled downstream in the caller?

**Comment by xellio** [comment]
PR that should solve this issue: https://github.com/lbuchs/WebAuthn/pull/95
